[default.general]
chip = "fe310-g002"
connect_under_reset = false

[default.probe]
protocol = "Jtag"

[default.flashing]
enabled = true
restore_unwritten_bytes = false
do_chip_erase = false

[default.reset]
enabled = true
halt_afterwards = false

[default.rtt]
enabled = false
